WTF_CSRF_ENABLED = True
SECRET_KEY = 'long-secret-key'

SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False

OAUTH_CLIENT_CACHE_TYPE = 'simple'
AUTHLIB_CACHE_TYPE = 'simple'

GOOGLE_CLIENT_KEY = ''
GOOGLE_CLIENT_SECRET = ''

FACEBOOK_CLIENT_KEY = ''
FACEBOOK_CLIENT_SECRET = ''

MAIL_SERVER = ''
MAIL_USERNAME = ''
MAIL_PASSWORD = ''
MAIL_DEFAULT_SENDER = ('ePrihlaska', 'prihlaska@mg.shu.io')
